version: "3"

volumes:
  ignore_dir:

services:
  app:
    restart: always
    build:
      context: .
      dockerfile: Dockerfile.m1
      args:
        - UID=${UID}
        - GID=${GID}
    command: /bin/sh -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ./:/app
      - ignore_dir:/app/tmp    # これはlocalに残って欲しくないから
      - ignore_dir:/app/public # これも
    ports:
      - 3000:3000
    depends_on:
      - db
#      - sidekiq
#      - stripe-mock
    env_file:
      - .env
    environment:
      RAILS_ENV: development
      DATABASE_HOST: db
    stdin_open: true
    tty: true

#  sidekiq:
#    restart: always
#    image: prob-works_app
#    command: sidekiq
#    volumes:
#      - ./:/app
#      - ignore_dir:/app/tmp
#      - ignore_dir:/app/public
#    depends_on:
#      - redis
#    env_file:
#      - .env
#    environment:
#      RAILS_ENV: development

  db:
    restart: always
    image: postgres:11
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: deploy
      POSTGRES_PASSWORD: password
    volumes:
      - ./tmp/db/data:/var/lib/postgresql/data

#  redis:
#    image: redis:5
#
#  stripe-mock:
#    image: stripemock/stripe-mock:v0.98.0